### ISSUE TITLE
i cant log in to any account and i get this error GET /api/v1/fbsearch/suggested_searches/?type=users - 404 Not Found;

### ISSUE THREAD

**Issue by iPnx36** [igdmapps/igdm#1467] opened 2022-02-16 23:42 UTC
![image](https://user-images.githubusercontent.com/69019151/154376141-b23894ea-5fcb-4a74-acdc-e5972a121a6f.png)

**Comment by mbahkemo** [comment] 2022-02-18 07:04
I don't see any response from developer ?

**Comment by iPnx36** [comment] 2022-02-18 08:01
yeah nothing 
i tried with 4 of my friends and they all have the same issue

**Comment by jmbflat** [comment] 2022-02-18 22:43
As a temporary workaround, since I'm building and running locally, I went into 
/IGDM/node_modules/instagram-private-api/dist/services/simulate.service.js 

and commented out the following lines to get it working:

//            () => this.client.fbsearch.suggestedSearches('users'),
//            () => this.client.fbsearch.suggestedSearches('blended'),

**Comment by iPnx36** [comment] 2022-02-19 09:23
didnt find /IGDM/node_modules/instagram-private-api/dist/services/simulate.service.js
do you have discord or any app i can contact you with plz ?

**Comment by inbomber** [comment] 2022-02-19 22:35
same issue here, any update?

**Comment by iPnx36** [comment] 2022-02-20 08:05
nop

**Comment by mbahkemo** [comment] 2022-02-21 02:33
keep monitor....still no update

**Comment by jmbflat** [comment] 2022-02-21 03:16
Problem is an update to instagram's api.  The local fix is to bump the version in package.js when building from:

"instagram-private-api": "^1.44.1",

to

"instagram-private-api": "^1.45.3"

while this works for me locally, it may break other things, so a project dev will have to manage the right way to do this.  If you are cloning the git project and running npm install and npm start, I can confirm this fixes the issue.  Could well break something else, so use at your own risk until a dev pushes an update

**Comment by iPnx36** [comment] 2022-02-21 12:40
i can login in, but its show's nothing

**Comment by mbahkemo** [comment] 2022-02-21 15:03
![image](https://user-images.githubusercontent.com/86633802/154980607-f1652795-fb6c-4d7b-a1f6-597e27c3f550.png)

Remain the same

**Comment by hugohamelcom** [comment] 2022-02-21 23:04
Same here

**Comment by mbahkemo** [comment] 2022-02-24 06:17
Any development there ?

**Comment by iPnx36** [comment] 2022-02-28 19:48
any update ?

**Comment by Wulfen123** [comment] 2022-03-18 20:36
This error is annoying af anyone got a fix for this?

**Comment by opdafd2** [comment] 2022-03-30 22:18
What can I do if I don't have node_modules in my IGdm folder? I tried changing the version in app.asar from 1.44.1 to 1.45.3  and IGdm just doesn't open anymore afterwards

this is how my folders look like
![a5ca54e33c6043de769633eb125df747](https://user-images.githubusercontent.com/100243682/160940009-dcb335b7-c244-4e7c-a137-d83dcc7f51ed.png)

![c5fd149d7de753527215b1ed177425f0](https://user-images.githubusercontent.com/100243682/160940281-49b8a03d-9391-47e8-b815-769b32b3c41e.png)

**Comment by ifedapoolarewaju** [comment] 2022-04-18 12:04
this issue is now fixed. Please download the latest version on igdm.me

**Closed by ifedapoolarewaju** 2022-04-18 12:04 UTC
